theme: jekyll-theme-minimal
title: My Resume
description:
show_downloads: True
header_pages:
  - https://github.com/joek47/cybersecurity/blob/gh-pages/index.md
  - https://github.com/joek47/machinelearning/blob/gh-pages/index.md
